name: Deploy to Fly.io

on:
  workflow_run:
    workflows:
      - "Elixir CI"
    branches: [ "main" ]
    types:
      - completed

permissions:
  contents: read

env:
  FLY_API_TOKEN: ${{ secrets.FLYDEPLOYTOKEN }}

jobs:
  deploy:

    name: Deploy to Fly.io
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
